### ISSUE TITLE
Vacant seats?

### ISSUE THREAD

**Issue by showerst** [openstates/people#15]
If we have the infrastructure for it, having a vacant.yml either in the root or each state would be a nice to have.

**Comment by jamesturk** [comment]
This makes sense to me, right now i'm just warning if seats are vacant in
the linter. I think the main change would either be to have that file
suppress those warnings or elevate that to an error if it isn't present

**Comment by jamesturk** [comment]
I was actually thinking that it might make sense to have a way to suppress
some of the other potential warnings, I added a checker that ensures URLs
are HTTPS (then commented it out for now since it was too aggressive given
the current status in many states) and have on my TODO List a checker
that'd look for duplicate phone numbers/etc.

For this I'd been thinking maybe a state would have some kind of exceptions
file:

nc/exceptions.yml

http_whitelist:
- http://example.com
reused_contact_info:
- phone: 1-800-44N-CLEG

for the cases where there's known questionable data.


Even if we do add that file, I can see the argument for vacancies to have
their own file, but curious if you thought there's a benefit there or if
they could be a key within the exceptions file.

Also either way, I think we should add an end_date/vacant_until so we start
getting warnings or errors again when the vacancy expires (so we don't
accidentally neglect one for a really long time)

vacancies:
- type: upper
  district: 12
  vacant_until: 2019-01-01

**Comment by jamesturk** [comment]
ok scratch the other validation as duplicate contact info checking also turned out to be more trouble than it was worth (I had no idea how many legislators shared phone numbers & even external addresses until today)

I'll take a look at adding this to the root

**Comment by jamesturk** [comment]
took a swing at this here:

https://github.com/openstates/people/compare/vacancies?expand=1#diff-98126fffe52a5bcbb73fa2926d7732dd

- I decided to just keep this in the existing districts list for now might make sense, won't be a big deal to move it
- implementation is really just decrementing the number of expected seats for that district if we're before the vacant_until date.  If we're past it throwing an error so that the date can either be fixed or vacancy removed.
