### ISSUE TITLE
Rhode Island House District 68

### ISSUE THREAD

**Issue by putorti** [openstates/people#152]
**OUT:** Laufton Ascencao resigned
**IN:** June Speakman

This happened on March 13
https://www.rwu.edu/news/news-archive/rwu-professor-june-speakman-sworn-rhode-island-house-representatives

**Comment by amydrummond** [comment]
I noticed that the contact information for Ascencao includes the photo and the url for Kenneth Marshall. This is reasonable considering that Ascencao never took office, and the retired Marshall took his place: https://www.providencejournal.com/news/20181213/incumbent-who-did-not-seek-reelection-will-remain-in-east-bay-house-seat-until-special-election.  I was about to make these corrections in a PR for the yaml, but ... should we consider him retired, since he never took office?

**Comment by jamesturk** [comment]
Ah that's a tricky one, but I think we'll consider them retired for this
purpose, since full removal would potentially cause issues if people had
the id in their system.

Thanks!
